import React, { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'te';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Comprehensive Translation Dictionary - 500+ translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // ========== NAVIGATION ==========
    'nav.dashboard': 'Dashboard',
    'nav.upload': 'Upload',
    'nav.map': 'Map',
    'nav.rewards': 'Rewards',
    'nav.community': 'Community',
    'nav.education': 'Education',
    'nav.leaderboard': 'Leaderboard',
    'nav.events': 'Events',
    'nav.analytics': 'Analytics',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.notifications': 'Notifications',
    'nav.findCenters': 'Find Centers',
    'nav.signIn': 'Sign In',
    'nav.logout': 'Logout',
    'nav.more': 'More',
    'nav.explore': 'Explore',
    'nav.navigation': 'Navigation',
    'nav.account': 'Account',
    
    // ========== LANDING PAGE ==========
    'landing.hero.badge': 'AI-Powered Solution',
    'landing.hero.title': 'Transform E-Waste into a Sustainable Future',
    'landing.hero.subtitle': 'Join thousands in making a difference. Our AI-powered platform makes e-waste management simple, rewarding, and impactful.',
    'landing.hero.getStarted': 'Get Started',
    'landing.hero.tryAI': 'Try AI Recognition',
    'landing.stats.users': 'Users Registered',
    'landing.stats.recycled': 'E-Waste Recycled',
    'landing.stats.centers': 'Collection Centers',
    'landing.stats.accuracy': 'AI Accuracy',
    'landing.features.title': 'Powerful Features',
    'landing.features.subtitle': 'Everything you need to manage e-waste responsibly and earn rewards while doing it',
    'landing.features.ai.title': 'AI Recognition',
    'landing.features.ai.desc': 'Instantly identify e-waste with advanced AI',
    'landing.features.map.title': 'Find Centers',
    'landing.features.map.desc': 'Locate nearby recycling facilities easily',
    'landing.features.rewards.title': 'Earn Rewards',
    'landing.features.rewards.desc': 'Get points for every device recycled',
    'landing.features.impact.title': 'Track Impact',
    'landing.features.impact.desc': 'See your environmental contribution',
    'landing.cta.title': 'Ready to Make a Difference?',
    'landing.cta.subtitle': 'Join our community of eco-warriors and start your journey towards a sustainable future. Every device recycled makes a difference.',
    'landing.cta.signup': 'Sign Up Now',
    
    // ========== LOGIN / REGISTER ==========
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInSubtitle': 'Sign in to your account to continue',
    'auth.createAccount': 'Create Account',
    'auth.signUpSubtitle': 'Join our community and start making a difference',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.phoneNumber': 'Phone Number',
    'auth.preferredLanguage': 'Preferred Language',
    'auth.selectRole': 'Select Role',
    'auth.role.user': 'Regular User',
    'auth.role.admin': 'Administrator',
    'auth.role.worker': 'Recycling Worker',
    'auth.role.organization': 'Organization',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUpLink': 'Sign up',
    'auth.signInLink': 'Sign in',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.rememberMe': 'Remember me',
    'auth.orContinueWith': 'Or continue with',
    'auth.google': 'Google',
    'auth.loginSuccess': 'Login successful',
    'auth.signupSuccess': 'Account created successfully',
    'auth.logoutSuccess': 'Logged out successfully',
    
    // ========== DASHBOARD ==========
    'dashboard.welcome': 'Welcome back',
    'dashboard.welcomeMessage': "Here's your environmental impact summary",
    'dashboard.overview': 'Overview',
    'dashboard.stats.recycled': 'Total E-Waste Recycled',
    'dashboard.stats.carbon': 'Carbon Footprint Saved',
    'dashboard.stats.points': 'Total Points Earned',
    'dashboard.stats.items': 'Items Processed',
    'dashboard.stats.rank': 'Global Rank',
    'dashboard.stats.level': 'Current Level',
    'dashboard.stats.streak': 'Day Streak',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.impactChart': 'Environmental Impact',
    'dashboard.monthlyProgress': 'Monthly Progress',
    'dashboard.achievements': 'Recent Achievements',
    'dashboard.uploadDevice': 'Upload Device',
    'dashboard.findCenter': 'Find Center',
    'dashboard.viewRewards': 'View Rewards',
    'dashboard.joinEvent': 'Join Event',
    'dashboard.learnMore': 'Learn More',
    'dashboard.seeAll': 'See All',
    'dashboard.noActivity': 'No recent activity',
    'dashboard.getStarted': 'Get started by uploading your first device',
    
    // ========== UPLOAD PAGE ==========
    'upload.title': 'Upload E-Waste for AI Recognition',
    'upload.subtitle': 'Upload images of your electronic waste for instant identification',
    'upload.dragDrop': 'Drag and drop images here, or click to browse',
    'upload.supportedFormats': 'Supported formats: JPG, PNG, WebP',
    'upload.maxSize': 'Max file size: 10MB',
    'upload.analyze': 'Analyze Device',
    'upload.analyzing': 'Analyzing...',
    'upload.results': 'Recognition Results',
    'upload.deviceType': 'Device Type',
    'upload.confidence': 'Confidence',
    'upload.condition': 'Condition',
    'upload.estimatedValue': 'Estimated Value',
    'upload.recyclingMethod': 'Recycling Method',
    'upload.nearestCenter': 'Nearest Center',
    'upload.schedule': 'Schedule Pickup',
    'upload.selfDrop': 'Self Drop-off',
    'upload.saveResults': 'Save Results',
    'upload.uploadAnother': 'Upload Another',
    'upload.history': 'Upload History',
    'upload.noResults': 'No results yet',
    'upload.uploadFirst': 'Upload your first device to see results',
    
    // ========== MAP PAGE ==========
    'map.title': 'Find Recycling Centers',
    'map.subtitle': 'Locate nearby e-waste collection facilities',
    'map.searchLocation': 'Search location...',
    'map.filterByService': 'Filter by Service',
    'map.allServices': 'All Services',
    'map.pickup': 'Pickup Available',
    'map.dropoff': 'Drop-off',
    'map.buyback': 'Buyback',
    'map.certified': 'Certified',
    'map.nearby': 'Nearby Centers',
    'map.distance': 'Distance',
    'map.openNow': 'Open Now',
    'map.closed': 'Closed',
    'map.opensAt': 'Opens at',
    'map.closesAt': 'Closes at',
    'map.getDirections': 'Get Directions',
    'map.callCenter': 'Call Center',
    'map.viewDetails': 'View Details',
    'map.services': 'Services',
    'map.hours': 'Operating Hours',
    'map.contact': 'Contact',
    'map.ratings': 'Ratings',
    'map.reviews': 'Reviews',
    
    // ========== REWARDS PAGE ==========
    'rewards.title': 'Rewards Shop',
    'rewards.subtitle': 'Redeem your points for exciting rewards',
    'rewards.yourPoints': 'Your Points',
    'rewards.availablePoints': 'Available Points',
    'rewards.pointsHistory': 'Points History',
    'rewards.redeem': 'Redeem',
    'rewards.redeemed': 'Redeemed',
    'rewards.pointsRequired': 'points',
    'rewards.categories': 'Categories',
    'rewards.all': 'All',
    'rewards.giftCards': 'Gift Cards',
    'rewards.products': 'Products',
    'rewards.vouchers': 'Vouchers',
    'rewards.donations': 'Donations',
    'rewards.inStock': 'In Stock',
    'rewards.outOfStock': 'Out of Stock',
    'rewards.confirmRedeem': 'Confirm Redemption',
    'rewards.confirmMessage': 'Are you sure you want to redeem this reward?',
    'rewards.success': 'Reward redeemed successfully!',
    'rewards.insufficient': 'Insufficient points',
    'rewards.myRewards': 'My Rewards',
    'rewards.noRewards': 'No rewards yet',
    'rewards.earnMore': 'Earn more points by recycling',
    
    // ========== COMMUNITY PAGE ==========
    'community.title': 'Community',
    'community.subtitle': 'Connect with eco-warriors worldwide',
    'community.feed': 'Community Feed',
    'community.trending': 'Trending',
    'community.following': 'Following',
    'community.myPosts': 'My Posts',
    'community.createPost': 'Create Post',
    'community.whatsOnMind': "What's on your mind?",
    'community.shareThoughts': 'Share your thoughts...',
    'community.post': 'Post',
    'community.cancel': 'Cancel',
    'community.like': 'Like',
    'community.comment': 'Comment',
    'community.share': 'Share',
    'community.follow': 'Follow',
    'community.unfollow': 'Unfollow',
    'community.likes': 'likes',
    'community.comments': 'comments',
    'community.replies': 'replies',
    'community.writeComment': 'Write a comment...',
    'community.viewMore': 'View more',
    'community.topContributors': 'Top Contributors',
    'community.suggestedUsers': 'Suggested Users',
    'community.noPosts': 'No posts yet',
    'community.beFirst': 'Be the first to post!',
    
    // ========== EDUCATION PAGE ==========
    'education.title': 'Education Center',
    'education.subtitle': 'Learn about e-waste management and sustainability',
    'education.courses': 'Courses',
    'education.guides': 'Guides',
    'education.videos': 'Videos',
    'education.quizzes': 'Quizzes',
    'education.certifications': 'Certifications',
    'education.browse': 'Browse Courses',
    'education.featured': 'Featured',
    'education.popular': 'Popular',
    'education.new': 'New',
    'education.beginner': 'Beginner',
    'education.intermediate': 'Intermediate',
    'education.advanced': 'Advanced',
    'education.enroll': 'Enroll Now',
    'education.enrolled': 'Enrolled',
    'education.continue': 'Continue',
    'education.completed': 'Completed',
    'education.progress': 'Progress',
    'education.lessons': 'Lessons',
    'education.duration': 'Duration',
    'education.certificate': 'Certificate',
    'education.takeQuiz': 'Take Quiz',
    'education.score': 'Score',
    'education.passed': 'Passed',
    'education.failed': 'Failed',
    'education.retake': 'Retake',
    
    // ========== LEADERBOARD PAGE ==========
    'leaderboard.title': 'Leaderboard',
    'leaderboard.subtitle': 'Top eco-warriors making a difference',
    'leaderboard.global': 'Global',
    'leaderboard.regional': 'Regional',
    'leaderboard.friends': 'Friends',
    'leaderboard.thisWeek': 'This Week',
    'leaderboard.thisMonth': 'This Month',
    'leaderboard.allTime': 'All Time',
    'leaderboard.rank': 'Rank',
    'leaderboard.user': 'User',
    'leaderboard.points': 'Points',
    'leaderboard.recycled': 'Recycled',
    'leaderboard.level': 'Level',
    'leaderboard.yourRank': 'Your Rank',
    'leaderboard.topPerformers': 'Top Performers',
    'leaderboard.risingStars': 'Rising Stars',
    'leaderboard.viewProfile': 'View Profile',
    'leaderboard.challenge': 'Challenge',
    'leaderboard.noData': 'No data available',
    
    // ========== EVENTS PAGE ==========
    'events.title': 'Events Calendar',
    'events.subtitle': 'Join community events and collection drives',
    'events.upcoming': 'Upcoming Events',
    'events.past': 'Past Events',
    'events.myEvents': 'My Events',
    'events.all': 'All Events',
    'events.workshops': 'Workshops',
    'events.drives': 'Collection Drives',
    'events.webinars': 'Webinars',
    'events.register': 'Register',
    'events.registered': 'Registered',
    'events.unregister': 'Unregister',
    'events.date': 'Date',
    'events.time': 'Time',
    'events.location': 'Location',
    'events.online': 'Online',
    'events.offline': 'Offline',
    'events.hybrid': 'Hybrid',
    'events.participants': 'Participants',
    'events.seats': 'Seats Available',
    'events.full': 'Event Full',
    'events.details': 'Event Details',
    'events.addToCalendar': 'Add to Calendar',
    'events.share': 'Share Event',
    'events.noEvents': 'No events scheduled',
    
    // ========== ANALYTICS PAGE ==========
    'analytics.title': 'Analytics & Reports',
    'analytics.subtitle': 'Track your environmental impact',
    'analytics.overview': 'Overview',
    'analytics.insights': 'Insights',
    'analytics.reports': 'Reports',
    'analytics.export': 'Export',
    'analytics.period': 'Period',
    'analytics.today': 'Today',
    'analytics.week': 'This Week',
    'analytics.month': 'This Month',
    'analytics.year': 'This Year',
    'analytics.custom': 'Custom Range',
    'analytics.totalImpact': 'Total Impact',
    'analytics.carbonSaved': 'Carbon Saved',
    'analytics.deviceTypes': 'Device Types',
    'analytics.recyclingTrends': 'Recycling Trends',
    'analytics.comparison': 'Comparison',
    'analytics.vsLastMonth': 'vs Last Month',
    'analytics.growth': 'Growth',
    'analytics.decline': 'Decline',
    'analytics.stable': 'Stable',
    'analytics.downloadPDF': 'Download PDF',
    'analytics.downloadCSV': 'Download CSV',
    'analytics.share': 'Share Report',
    
    // ========== ADMIN PAGE ==========
    'admin.title': 'Admin Panel',
    'admin.subtitle': 'Manage platform and users',
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.content': 'Content',
    'admin.settings': 'Settings',
    'admin.reports': 'Reports',
    'admin.totalUsers': 'Total Users',
    'admin.activeUsers': 'Active Users',
    'admin.newUsers': 'New Users',
    'admin.totalCenters': 'Total Centers',
    'admin.pendingApprovals': 'Pending Approvals',
    'admin.userManagement': 'User Management',
    'admin.searchUsers': 'Search users...',
    'admin.filterByRole': 'Filter by Role',
    'admin.filterByStatus': 'Filter by Status',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.suspended': 'Suspended',
    'admin.viewUser': 'View User',
    'admin.editUser': 'Edit User',
    'admin.suspendUser': 'Suspend User',
    'admin.deleteUser': 'Delete User',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.bulkActions': 'Bulk Actions',
    'admin.export': 'Export',
    'admin.systemSettings': 'System Settings',
    'admin.notifications': 'Notifications',
    'admin.maintenance': 'Maintenance',
    
    // ========== PROFILE PAGE ==========
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your account and preferences',
    'profile.personalInfo': 'Personal Information',
    'profile.accountSettings': 'Account Settings',
    'profile.privacy': 'Privacy',
    'profile.security': 'Security',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.name': 'Full Name',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.bio': 'Bio',
    'profile.location': 'Location',
    'profile.website': 'Website',
    'profile.language': 'Language',
    'profile.timezone': 'Timezone',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.emailNotifications': 'Email Notifications',
    'profile.pushNotifications': 'Push Notifications',
    'profile.smsNotifications': 'SMS Notifications',
    'profile.publicProfile': 'Public Profile',
    'profile.showStats': 'Show Statistics',
    'profile.showActivity': 'Show Activity',
    'profile.deleteAccount': 'Delete Account',
    'profile.deactivateAccount': 'Deactivate Account',
    'profile.verified': 'Verified',
    'profile.notVerified': 'Not Verified',
    'profile.verify': 'Verify',
    
    // ========== NOTIFICATIONS PAGE ==========
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Stay updated with your activity',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.read': 'Read',
    'notifications.markAllRead': 'Mark All as Read',
    'notifications.clear': 'Clear All',
    'notifications.settings': 'Notification Settings',
    'notifications.noNew': 'No new notifications',
    'notifications.noNotifications': 'No notifications yet',
    'notifications.empty': "You're all caught up!",
    'notifications.types.system': 'System',
    'notifications.types.rewards': 'Rewards',
    'notifications.types.community': 'Community',
    'notifications.types.events': 'Events',
    'notifications.types.admin': 'Admin',
    'notifications.delete': 'Delete',
    'notifications.mute': 'Mute',
    'notifications.unmute': 'Unmute',
    
    // ========== COMMON ELEMENTS ==========
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.viewAll': 'View All',
    'common.showMore': 'Show More',
    'common.showLess': 'Show Less',
    'common.learnMore': 'Learn More',
    'common.readMore': 'Read More',
    'common.seeAll': 'See All',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.submit': 'Submit',
    'common.send': 'Send',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.copied': 'Copied!',
    'common.update': 'Update',
    'common.refresh': 'Refresh',
    'common.retry': 'Retry',
    'common.undo': 'Undo',
    'common.redo': 'Redo',
    'common.settings': 'Settings',
    'common.help': 'Help',
    'common.support': 'Support',
    'common.feedback': 'Feedback',
    'common.report': 'Report',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.select': 'Select',
    'common.choose': 'Choose',
    'common.browse': 'Browse',
    'common.noResults': 'No results found',
    'common.noData': 'No data available',
    'common.comingSoon': 'Coming Soon',
    'common.new': 'New',
    'common.popular': 'Popular',
    'common.featured': 'Featured',
    'common.recommended': 'Recommended',
    'common.trending': 'Trending',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.thisWeek': 'This Week',
    'common.thisMonth': 'This Month',
    'common.thisYear': 'This Year',
    'common.total': 'Total',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.pending': 'Pending',
    'common.completed': 'Completed',
    'common.failed': 'Failed',
    'common.processing': 'Processing',
    'common.kg': 'kg',
    'common.points': 'points',
    'common.level': 'Level',
    'common.rank': 'Rank',
    
    // ========== TIME & DATES ==========
    'time.justNow': 'Just now',
    'time.minuteAgo': 'minute ago',
    'time.minutesAgo': 'minutes ago',
    'time.hourAgo': 'hour ago',
    'time.hoursAgo': 'hours ago',
    'time.dayAgo': 'day ago',
    'time.daysAgo': 'days ago',
    'time.weekAgo': 'week ago',
    'time.weeksAgo': 'weeks ago',
    'time.monthAgo': 'month ago',
    'time.monthsAgo': 'months ago',
    'time.yearAgo': 'year ago',
    'time.yearsAgo': 'years ago',
    
    // ========== ERROR MESSAGES ==========
    'error.general': 'Something went wrong',
    'error.network': 'Network error. Please check your connection',
    'error.notFound': 'Not found',
    'error.unauthorized': 'Unauthorized access',
    'error.forbidden': 'Access forbidden',
    'error.serverError': 'Server error. Please try again later',
    'error.invalidInput': 'Invalid input',
    'error.required': 'This field is required',
    'error.invalidEmail': 'Invalid email address',
    'error.invalidPhone': 'Invalid phone number',
    'error.passwordMismatch': 'Passwords do not match',
    'error.weakPassword': 'Password is too weak',
    'error.uploadFailed': 'Upload failed',
    'error.deleteFailed': 'Delete failed',
    'error.updateFailed': 'Update failed',
    
    // ========== SUCCESS MESSAGES ==========
    'success.saved': 'Saved successfully',
    'success.updated': 'Updated successfully',
    'success.deleted': 'Deleted successfully',
    'success.uploaded': 'Uploaded successfully',
    'success.sent': 'Sent successfully',
    'success.copied': 'Copied to clipboard',
    
    // ========== LANGUAGE SELECTOR ==========
    'language.select': 'Select Language',
    'language.english': 'English',
    'language.hindi': 'हिन्दी (Hindi)',
    'language.telugu': 'తెలుగు (Telugu)',
  },
  
  hi: {
    // ========== नेविगेशन ==========
    'nav.dashboard': 'डैशबोर्ड',
    'nav.upload': 'अपलोड',
    'nav.map': 'मानचित्र',
    'nav.rewards': 'पुरस्कार',
    'nav.community': 'समुदाय',
    'nav.education': 'शिक्षा',
    'nav.leaderboard': 'लीडरबोर्ड',
    'nav.events': 'कार्यक्रम',
    'nav.analytics': 'विश्लेषण',
    'nav.admin': 'एडमिन',
    'nav.profile': 'प्रोफाइल',
    'nav.notifications': 'सूचनाएं',
    'nav.findCenters': 'केंद्र खोजें',
    'nav.signIn': 'साइन इन करें',
    'nav.logout': 'लॉग आउट',
    'nav.more': 'अधिक',
    'nav.explore': 'एक्सप्लोर',
    'nav.navigation': 'नेविगेशन',
    'nav.account': 'खाता',
    
    // ========== लैंडिंग पेज ==========
    'landing.hero.badge': 'एआई-संचालित समाधान',
    'landing.hero.title': 'ई-कचरे को एक स्थायी भविष्य में बदलें',
    'landing.hero.subtitle': 'हजारों लोगों के साथ बदलाव लाएं। हमारा एआई-संचालित प्लेटफॉर्म ई-कचरा प्रबंधन को सरल, पुरस्कृत और प्रभावशाली बनाता है।',
    'landing.hero.getStarted': 'शुरू करें',
    'landing.hero.tryAI': 'एआई पहचान आजमाएं',
    'landing.stats.users': 'पंजीकृत उपयोगकर्ता',
    'landing.stats.recycled': 'ई-कचरा पुनर्नवीनीकरण',
    'landing.stats.centers': 'संग्रह केंद्र',
    'landing.stats.accuracy': 'एआई सटीकता',
    'landing.features.title': 'शक्तिशाली सुविधाएँ',
    'landing.features.subtitle': 'ई-कचरे को जिम्मेदारी से प्रबंधित करने और पुरस्कार अर्जित करने के लिए आवश्यक सब कुछ',
    'landing.features.ai.title': 'एआई पहचान',
    'landing.features.ai.desc': 'उन्नत एआई के साथ तुरंत ई-कचरे की पहचान करें',
    'landing.features.map.title': 'केंद्र खोजें',
    'landing.features.map.desc': 'आसानी से आस-पास की रीसाइक्लिंग सुविधाएं खोजें',
    'landing.features.rewards.title': 'पुरस्कार अर्जित करें',
    'landing.features.rewards.desc': 'हर पुनर्नवीनीकृत उपकरण के लिए अंक प्राप्त करें',
    'landing.features.impact.title': 'प्रभाव ट्रैक करें',
    'landing.features.impact.desc': 'अपना पर्यावरणीय योगदान देखें',
    'landing.cta.title': 'बदलाव लाने के लिए तैयार हैं?',
    'landing.cta.subtitle': 'इको-योद्धाओं के हमारे समुदाय में शामिल हों और एक स्थायी भविष्य की ओर अपनी यात्रा शुरू करें। हर पुनर्नवीनीकृत उपकरण मायने रखता है।',
    'landing.cta.signup': 'अभी साइन अप करें',
    
    // ========== लॉगिन / रजिस्टर ==========
    'auth.welcomeBack': 'वापसी पर स्वागत है',
    'auth.signInSubtitle': 'जारी रखने के लिए अपने खाते में साइन इन करें',
    'auth.createAccount': 'खाता बनाएं',
    'auth.signUpSubtitle': 'हमारे समुदाय में शामिल हों और बदलाव लाना शुरू करें',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.fullName': 'पूरा नाम',
    'auth.phoneNumber': 'फोन नंबर',
    'auth.preferredLanguage': 'पसंदीदा भाषा',
    'auth.selectRole': 'भूमिका चुनें',
    'auth.role.user': 'नियमित उपयोगकर्ता',
    'auth.role.admin': 'प्रशासक',
    'auth.role.worker': 'रीसाइक्लिंग कार्यकर्ता',
    'auth.role.organization': 'संगठन',
    'auth.signIn': 'साइन इन करें',
    'auth.signUp': 'साइन अप करें',
    'auth.noAccount': 'खाता नहीं है?',
    'auth.hasAccount': 'पहले से खाता है?',
    'auth.signUpLink': 'साइन अप करें',
    'auth.signInLink': 'साइन इन करें',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.rememberMe': 'मुझे याद रखें',
    'auth.orContinueWith': 'या जारी रखें',
    'auth.google': 'गूगल',
    'auth.loginSuccess': 'लॉगिन सफल',
    'auth.signupSuccess': 'खाता सफलतापूर्वक बनाया गया',
    'auth.logoutSuccess': 'सफलतापूर्वक लॉग आउट किया गया',
    
    // ========== डैशबोर्ड ==========
    'dashboard.welcome': 'स्वागत है',
    'dashboard.welcomeMessage': 'यहां आपका पर्यावरणीय प्रभाव सारांश है',
    'dashboard.overview': 'अवलोकन',
    'dashboard.stats.recycled': 'कुल ई-कचरा पुनर्नवीनीकरण',
    'dashboard.stats.carbon': 'कार्बन फुटप्रिंट बचाया',
    'dashboard.stats.points': 'कुल अंक अर्जित',
    'dashboard.stats.items': 'आइटम संसाधित',
    'dashboard.stats.rank': 'वैश्विक रैंक',
    'dashboard.stats.level': 'वर्तमान स्तर',
    'dashboard.stats.streak': 'दिन की लकीर',
    'dashboard.recentActivity': 'हाल की गतिविधि',
    'dashboard.quickActions': 'त्वरित कार्रवाई',
    'dashboard.impactChart': 'पर्यावरणीय प्रभाव',
    'dashboard.monthlyProgress': 'मासिक प्रगति',
    'dashboard.achievements': 'हालिया उपलब्धियां',
    'dashboard.uploadDevice': 'डिवाइस अपलोड करें',
    'dashboard.findCenter': 'केंद्र खोजें',
    'dashboard.viewRewards': 'पुरस्कार देखें',
    'dashboard.joinEvent': 'कार्यक्रम में शामिल हों',
    'dashboard.learnMore': 'और जानें',
    'dashboard.seeAll': 'सभी देखें',
    'dashboard.noActivity': 'कोई हालिया गतिविधि नहीं',
    'dashboard.getStarted': 'अपना पहला डिवाइस अपलोड करके शुरुआत करें',
    
    // ========== अपलोड पेज ==========
    'upload.title': 'एआई पहचान के लिए ई-कचरा अपलोड करें',
    'upload.subtitle': 'तत्काल पहचान के लिए अपने इलेक्ट्रॉनिक कचरे की छवियां अपलोड करें',
    'upload.dragDrop': 'यहां छवियां खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें',
    'upload.supportedFormats': 'समर्थित प्रारूप: JPG, PNG, WebP',
    'upload.maxSize': 'अधिकतम फ़ाइल आकार: 10MB',
    'upload.analyze': 'डिवाइस का विश्लेषण करें',
    'upload.analyzing': 'विश्लेषण हो रहा है...',
    'upload.results': 'पहचान परिणाम',
    'upload.deviceType': 'डिवाइस प्रकार',
    'upload.confidence': 'आत्मविश्वास',
    'upload.condition': 'स्थिति',
    'upload.estimatedValue': 'अनुमानित मूल्य',
    'upload.recyclingMethod': 'पुनर्चक्रण विधि',
    'upload.nearestCenter': 'निकटतम केंद्र',
    'upload.schedule': 'पिकअप शेड्यूल करें',
    'upload.selfDrop': 'स्वयं ड्रॉप-ऑफ',
    'upload.saveResults': 'परिणाम सहेजें',
    'upload.uploadAnother': 'एक और अपलोड करें',
    'upload.history': 'अपलोड इतिहास',
    'upload.noResults': 'अभी तक कोई परिणाम नहीं',
    'upload.uploadFirst': 'परिणाम देखने के लिए अपना पहला डिवाइस अपलोड करें',
    
    // ========== मानचित्र पेज ==========
    'map.title': 'रीसाइक्लिंग केंद्र खोजें',
    'map.subtitle': 'आस-पास की ई-कचरा संग्रह सुविधाएं खोजें',
    'map.searchLocation': 'स्थान खोजें...',
    'map.filterByService': 'सेवा के अनुसार फ़िल्टर करें',
    'map.allServices': 'सभी सेवाएं',
    'map.pickup': 'पिकअप उपलब्ध',
    'map.dropoff': 'ड्रॉप-ऑफ',
    'map.buyback': 'बायबैक',
    'map.certified': 'प्रमाणित',
    'map.nearby': 'आस-पास के केंद्र',
    'map.distance': 'दूरी',
    'map.openNow': 'अब खुला',
    'map.closed': 'बंद',
    'map.opensAt': 'खुलता है',
    'map.closesAt': 'बंद होता है',
    'map.getDirections': 'दिशा-निर्देश प्राप्त करें',
    'map.callCenter': 'केंद्र पर कॉल करें',
    'map.viewDetails': 'विवरण देखें',
    'map.services': 'सेवाएं',
    'map.hours': 'संचालन के घंटे',
    'map.contact': 'संपर्क',
    'map.ratings': 'रेटिंग',
    'map.reviews': 'समीक्षाएं',
    
    // ========== पुरस्कार पेज ==========
    'rewards.title': 'पुरस्कार की दुकान',
    'rewards.subtitle': 'रोमांचक पुरस्कारों के लिए अपने अंकों को भुनाएं',
    'rewards.yourPoints': 'आपके अंक',
    'rewards.availablePoints': 'उपलब्ध अंक',
    'rewards.pointsHistory': 'अंक इतिहास',
    'rewards.redeem': 'भुनाएं',
    'rewards.redeemed': 'भुनाया गया',
    'rewards.pointsRequired': 'अंक',
    'rewards.categories': 'श्रेणियां',
    'rewards.all': 'सभी',
    'rewards.giftCards': 'गिफ्ट कार्ड',
    'rewards.products': 'उत्पाद',
    'rewards.vouchers': 'वाउचर',
    'rewards.donations': 'दान',
    'rewards.inStock': 'स्टॉक में',
    'rewards.outOfStock': 'स्टॉक से बाहर',
    'rewards.confirmRedeem': 'भुनाने की पुष्टि करें',
    'rewards.confirmMessage': 'क्या आप निश्चित रूप से इस पुरस्कार को भुनाना चाहते हैं?',
    'rewards.success': 'पुरस्कार सफलतापूर्वक भुनाया गया!',
    'rewards.insufficient': 'अपर्याप्त अंक',
    'rewards.myRewards': 'मेरे पुरस्कार',
    'rewards.noRewards': 'अभी तक कोई पुरस्कार नहीं',
    'rewards.earnMore': 'पुनर्चक्रण करके अधिक अंक अर्जित करें',
    
    // ========== समुदाय पेज ==========
    'community.title': 'समुदाय',
    'community.subtitle': 'दुनिया भर के इको-योद्धाओं से जुड़ें',
    'community.feed': 'समुदाय फ़ीड',
    'community.trending': 'ट्रेंडिंग',
    'community.following': 'फॉलो कर रहे हैं',
    'community.myPosts': 'मेरी पोस्ट',
    'community.createPost': 'पोस्ट बनाएं',
    'community.whatsOnMind': 'आपके मन में क्या है?',
    'community.shareThoughts': 'अपने विचार साझा करें...',
    'community.post': 'पोस्ट करें',
    'community.cancel': 'रद्द करें',
    'community.like': 'लाइक',
    'community.comment': 'टिप्पणी',
    'community.share': 'शेयर',
    'community.follow': 'फॉलो करें',
    'community.unfollow': 'अनफॉलो करें',
    'community.likes': 'लाइक',
    'community.comments': 'टिप्पणियां',
    'community.replies': 'जवाब',
    'community.writeComment': 'एक टिप्पणी लिखें...',
    'community.viewMore': 'और देखें',
    'community.topContributors': 'शीर्ष योगदानकर्ता',
    'community.suggestedUsers': 'सुझाए गए उपयोगकर्ता',
    'community.noPosts': 'अभी तक कोई पोस्ट नहीं',
    'community.beFirst': 'पोस्ट करने वाले पहले व्यक्ति बनें!',
    
    // ========== शिक्षा पेज ==========
    'education.title': 'शिक्षा केंद्र',
    'education.subtitle': 'ई-कचरा प्रबंधन और स्थिरता के बारे में जानें',
    'education.courses': 'पाठ्यक्रम',
    'education.guides': 'गाइड',
    'education.videos': 'वीडियो',
    'education.quizzes': 'क्विज़',
    'education.certifications': 'प्रमाणपत्र',
    'education.browse': 'पाठ्यक्रम ब्राउज़ करें',
    'education.featured': 'चुनिंदा',
    'education.popular': 'लोकप्रिय',
    'education.new': 'नया',
    'education.beginner': 'शुरुआती',
    'education.intermediate': 'मध्यवर्ती',
    'education.advanced': 'उन्नत',
    'education.enroll': 'अभी नामांकन करें',
    'education.enrolled': 'नामांकित',
    'education.continue': 'जारी रखें',
    'education.completed': 'पूर्ण',
    'education.progress': 'प्रगति',
    'education.lessons': 'पाठ',
    'education.duration': 'अवधि',
    'education.certificate': 'प्रमाणपत्र',
    'education.takeQuiz': 'क्विज़ लें',
    'education.score': 'स्कोर',
    'education.passed': 'पास',
    'education.failed': 'असफल',
    'education.retake': 'फिर से लें',
    
    // ========== लीडरबोर्ड पेज ==========
    'leaderboard.title': 'लीडरबोर्ड',
    'leaderboard.subtitle': 'बदलाव लाने वाले शीर्ष इको-योद्धा',
    'leaderboard.global': 'वैश्विक',
    'leaderboard.regional': 'क्षेत्रीय',
    'leaderboard.friends': 'दोस्त',
    'leaderboard.thisWeek': 'इस सप्ताह',
    'leaderboard.thisMonth': 'इस महीने',
    'leaderboard.allTime': 'सर्वकालिक',
    'leaderboard.rank': 'रैंक',
    'leaderboard.user': 'उपयोगकर्ता',
    'leaderboard.points': 'अंक',
    'leaderboard.recycled': 'पुनर्नवीनीकृत',
    'leaderboard.level': 'स्तर',
    'leaderboard.yourRank': 'आपकी रैंक',
    'leaderboard.topPerformers': 'शीर्ष प्रदर्शनकर्ता',
    'leaderboard.risingStars': 'उभरते सितारे',
    'leaderboard.viewProfile': 'प्रोफाइल देखें',
    'leaderboard.challenge': 'चुनौती',
    'leaderboard.noData': 'कोई डेटा उपलब्ध नहीं',
    
    // ========== कार्यक्रम पेज ==========
    'events.title': 'कार्यक्रम कैलेंडर',
    'events.subtitle': 'सामुदायिक कार्यक्रमों और संग्रह अभियानों में शामिल हों',
    'events.upcoming': 'आगामी कार्यक्रम',
    'events.past': 'पिछले कार्यक्रम',
    'events.myEvents': 'मेरे कार्यक्रम',
    'events.all': 'सभी कार्यक्रम',
    'events.workshops': 'कार्यशालाएं',
    'events.drives': 'संग्रह अभियान',
    'events.webinars': 'वेबिनार',
    'events.register': 'पंजीकरण करें',
    'events.registered': 'पंजीकृत',
    'events.unregister': 'पंजीकरण रद्द करें',
    'events.date': 'तिथि',
    'events.time': 'समय',
    'events.location': 'स्थान',
    'events.online': 'ऑनलाइन',
    'events.offline': 'ऑफलाइन',
    'events.hybrid': 'हाइब्रिड',
    'events.participants': 'प्रतिभागी',
    'events.seats': 'सीटें उपलब्ध',
    'events.full': 'कार्यक्रम भरा हुआ',
    'events.details': 'कार्यक्रम विवरण',
    'events.addToCalendar': 'कैलेंडर में जोड़ें',
    'events.share': 'कार्यक्रम साझा करें',
    'events.noEvents': 'कोई कार्यक्रम निर्धारित नहीं',
    
    // ========== विश्लेषण पेज ==========
    'analytics.title': 'विश्लेषण और रिपोर्ट',
    'analytics.subtitle': 'अपने पर्यावरणीय प्रभाव को ट्रैक करें',
    'analytics.overview': 'अवलोकन',
    'analytics.insights': 'अंतर्दृष्टि',
    'analytics.reports': 'रिपोर्ट',
    'analytics.export': 'निर्यात',
    'analytics.period': 'अवधि',
    'analytics.today': 'आज',
    'analytics.week': 'इस सप्ताह',
    'analytics.month': 'इस महीने',
    'analytics.year': 'इस वर्ष',
    'analytics.custom': 'कस्टम रेंज',
    'analytics.totalImpact': 'कुल प्रभाव',
    'analytics.carbonSaved': 'कार्बन बचाया',
    'analytics.deviceTypes': 'डिवाइस प्रकार',
    'analytics.recyclingTrends': 'पुनर्चक्रण रुझान',
    'analytics.comparison': 'तुलना',
    'analytics.vsLastMonth': 'पिछले महीने की तुलना में',
    'analytics.growth': 'वृद्धि',
    'analytics.decline': 'गिरावट',
    'analytics.stable': 'स्थिर',
    'analytics.downloadPDF': 'PDF डाउनलोड करें',
    'analytics.downloadCSV': 'CSV डाउनलोड करें',
    'analytics.share': 'रिपोर्ट साझा करें',
    
    // ========== एडमिन पेज ==========
    'admin.title': 'एडमिन पैनल',
    'admin.subtitle': 'प्लेटफॉर्म और उपयोगकर्ताओं का प्रबंधन करें',
    'admin.dashboard': 'डैशबोर्ड',
    'admin.users': 'उपयोगकर्ता',
    'admin.content': 'सामग्री',
    'admin.settings': 'सेटिंग्स',
    'admin.reports': 'रिपोर्ट',
    'admin.totalUsers': 'कुल उपयोगकर्ता',
    'admin.activeUsers': 'सक्रिय उपयोगकर्ता',
    'admin.newUsers': 'नए उपयोगकर्ता',
    'admin.totalCenters': 'कुल केंद्र',
    'admin.pendingApprovals': 'लंबित स्वीकृतियां',
    'admin.userManagement': 'उपयोगकर्ता प्रबंधन',
    'admin.searchUsers': 'उपयोगकर्ता खोजें...',
    'admin.filterByRole': 'भूमिका के अनुसार फ़िल्टर करें',
    'admin.filterByStatus': 'स्थिति के अनुसार फ़िल्टर करें',
    'admin.active': 'सक्रिय',
    'admin.inactive': 'निष्क्रिय',
    'admin.suspended': 'निलंबित',
    'admin.viewUser': 'उपयोगकर्ता देखें',
    'admin.editUser': 'उपयोगकर्ता संपादित करें',
    'admin.suspendUser': 'उपयोगकर्ता निलंबित करें',
    'admin.deleteUser': 'उपयोगकर्ता हटाएं',
    'admin.approve': 'स्वीकृत करें',
    'admin.reject': 'अस्वीकार करें',
    'admin.bulkActions': 'थोक कार्रवाई',
    'admin.export': 'निर्यात',
    'admin.systemSettings': 'सिस्टम सेटिंग्स',
    'admin.notifications': 'सूचनाएं',
    'admin.maintenance': 'रखरखाव',
    
    // ========== प्रोफाइल पेज ==========
    'profile.title': 'प्रोफाइल',
    'profile.subtitle': 'अपने खाते और प्राथमिकताओं का प्रबंधन करें',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.accountSettings': 'खाता सेटिंग्स',
    'profile.privacy': 'गोपनीयता',
    'profile.security': 'सुरक्षा',
    'profile.edit': 'प्रोफाइल संपादित करें',
    'profile.save': 'परिवर्तन सहेजें',
    'profile.cancel': 'रद्द करें',
    'profile.name': 'पूरा नाम',
    'profile.email': 'ईमेल पता',
    'profile.phone': 'फोन नंबर',
    'profile.bio': 'बायो',
    'profile.location': 'स्थान',
    'profile.website': 'वेबसाइट',
    'profile.language': 'भाषा',
    'profile.timezone': 'समय क्षेत्र',
    'profile.changePassword': 'पासवर्ड बदलें',
    'profile.currentPassword': 'वर्तमान पासवर्ड',
    'profile.newPassword': 'नया पासवर्ड',
    'profile.confirmPassword': 'नए पासवर्ड की पुष्टि करें',
    'profile.emailNotifications': 'ईमेल सूचनाएं',
    'profile.pushNotifications': 'पुश सूचनाएं',
    'profile.smsNotifications': 'SMS सूचनाएं',
    'profile.publicProfile': 'सार्वजनिक प्रोफाइल',
    'profile.showStats': 'आंकड़े दिखाएं',
    'profile.showActivity': 'गतिविधि दिखाएं',
    'profile.deleteAccount': 'खाता हटाएं',
    'profile.deactivateAccount': 'खाता निष्क्रिय करें',
    'profile.verified': 'सत्यापित',
    'profile.notVerified': 'सत्यापित नहीं',
    'profile.verify': 'सत्यापित करें',
    
    // ========== सूचनाएं पेज ==========
    'notifications.title': 'सूचनाएं',
    'notifications.subtitle': 'अपनी गतिविधि के साथ अपडेट रहें',
    'notifications.all': 'सभी',
    'notifications.unread': 'अपठित',
    'notifications.read': 'पठित',
    'notifications.markAllRead': 'सभी को पढ़ा हुआ चिह्नित करें',
    'notifications.clear': 'सभी साफ़ करें',
    'notifications.settings': 'सूचना सेटिंग्स',
    'notifications.noNew': 'कोई नई सूचना नहीं',
    'notifications.noNotifications': 'अभी तक कोई सूचना नहीं',
    'notifications.empty': 'आप सब पकड़ लिए हैं!',
    'notifications.types.system': 'सिस्टम',
    'notifications.types.rewards': 'पुरस्कार',
    'notifications.types.community': 'समुदाय',
    'notifications.types.events': 'कार्यक्रम',
    'notifications.types.admin': 'एडमिन',
    'notifications.delete': 'हटाएं',
    'notifications.mute': 'म्यूट करें',
    'notifications.unmute': 'अनम्यूट करें',
    
    // ========== सामान्य तत्व ==========
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.confirm': 'पुष्टि करें',
    'common.close': 'बंद करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.sort': 'क्रमबद्ध करें',
    'common.view': 'देखें',
    'common.viewAll': 'सभी देखें',
    'common.showMore': 'और दिखाएं',
    'common.showLess': 'कम दिखाएं',
    'common.learnMore': 'और जानें',
    'common.readMore': 'और पढ़ें',
    'common.seeAll': 'सभी देखें',
    'common.yes': 'हां',
    'common.no': 'नहीं',
    'common.ok': 'ठीक है',
    'common.apply': 'लागू करें',
    'common.reset': 'रीसेट करें',
    'common.clear': 'साफ़ करें',
    'common.submit': 'जमा करें',
    'common.send': 'भेजें',
    'common.upload': 'अपलोड करें',
    'common.download': 'डाउनलोड करें',
    'common.share': 'साझा करें',
    'common.copy': 'कॉपी करें',
    'common.copied': 'कॉपी किया गया!',
    'common.update': 'अपडेट करें',
    'common.refresh': 'रिफ्रेश करें',
    'common.retry': 'पुनः प्रयास करें',
    'common.undo': 'पूर्ववत करें',
    'common.redo': 'फिर से करें',
    'common.settings': 'सेटिंग्स',
    'common.help': 'सहायता',
    'common.support': 'समर्थन',
    'common.feedback': 'फीडबैक',
    'common.report': 'रिपोर्ट करें',
    'common.success': 'सफलता',
    'common.error': 'त्रुटि',
    'common.warning': 'चेतावनी',
    'common.info': 'जानकारी',
    'common.required': 'आवश्यक',
    'common.optional': 'वैकल्पिक',
    'common.select': 'चुनें',
    'common.choose': 'चुनें',
    'common.browse': 'ब्राउज़ करें',
    'common.noResults': 'कोई परिणाम नहीं मिला',
    'common.noData': 'कोई डेटा उपलब्ध नहीं',
    'common.comingSoon': 'जल्द आ रहा है',
    'common.new': 'नया',
    'common.popular': 'लोकप्रिय',
    'common.featured': 'चुनिंदा',
    'common.recommended': 'अनुशंसित',
    'common.trending': 'ट्रेंडिंग',
    'common.today': 'आज',
    'common.yesterday': 'कल',
    'common.thisWeek': 'इस सप्ताह',
    'common.thisMonth': 'इस महीने',
    'common.thisYear': 'इस वर्ष',
    'common.total': 'कुल',
    'common.active': 'सक्रिय',
    'common.inactive': 'निष्क्रिय',
    'common.pending': 'लंबित',
    'common.completed': 'पूर्ण',
    'common.failed': 'असफल',
    'common.processing': 'प्रसंस्करण',
    'common.kg': 'किग्रा',
    'common.points': 'अंक',
    'common.level': 'स्तर',
    'common.rank': 'रैंक',
    
    // ========== समय और तिथियां ==========
    'time.justNow': 'अभी',
    'time.minuteAgo': 'मिनट पहले',
    'time.minutesAgo': 'मिनट पहले',
    'time.hourAgo': 'घंटा पहले',
    'time.hoursAgo': 'घंटे पहले',
    'time.dayAgo': 'दिन पहले',
    'time.daysAgo': 'दिन पहले',
    'time.weekAgo': 'सप्ताह पहले',
    'time.weeksAgo': 'सप्ताह पहले',
    'time.monthAgo': 'महीना पहले',
    'time.monthsAgo': 'महीने पहले',
    'time.yearAgo': 'वर्ष पहले',
    'time.yearsAgo': 'वर्ष पहले',
    
    // ========== त्रुटि संदेश ==========
    'error.general': 'कुछ गलत हो गया',
    'error.network': 'नेटवर्क त्रुटि। कृपया अपना कनेक्शन जांचें',
    'error.notFound': 'नहीं मिला',
    'error.unauthorized': 'अनधिकृत पहुंच',
    'error.forbidden': 'पहुंच निषिद्ध',
    'error.serverError': 'सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें',
    'error.invalidInput': 'अमान्य इनपुट',
    'error.required': 'यह फ़ील्ड आवश्यक है',
    'error.invalidEmail': 'अमान्य ईमेल पता',
    'error.invalidPhone': 'अमान्य फोन नंबर',
    'error.passwordMismatch': 'पासवर्ड मेल नहीं खाते',
    'error.weakPassword': 'पासवर्ड बहुत कमजोर है',
    'error.uploadFailed': 'अपलोड विफल',
    'error.deleteFailed': 'हटाना विफल',
    'error.updateFailed': 'अपडेट विफल',
    
    // ========== सफलता संदेश ==========
    'success.saved': 'सफलतापूर्वक सहेजा गया',
    'success.updated': 'सफलतापूर्वक अपडेट किया गया',
    'success.deleted': 'सफलतापूर्वक हटाया गया',
    'success.uploaded': 'सफलतापूर्वक अपलोड किया गया',
    'success.sent': 'सफलतापूर्वक भेजा गया',
    'success.copied': 'क्लिपबोर्ड पर कॉपी किया गया',
    
    // ========== भाषा चयनकर्ता ==========
    'language.select': 'भाषा चुनें',
    'language.english': 'English',
    'language.hindi': 'हिन्दी (Hindi)',
    'language.telugu': 'తెలుగు (Telugu)',
  },
  
  te: {
    // ========== నావిగేషన్ ==========
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.upload': 'అప్‌లోడ్',
    'nav.map': 'మ్యాప్',
    'nav.rewards': 'రివార్డ్స్',
    'nav.community': 'కమ్యూనిటీ',
    'nav.education': 'విద్య',
    'nav.leaderboard': 'లీడర్‌బోర్డ్',
    'nav.events': 'ఈవెంట్స్',
    'nav.analytics': 'విశ్లేషణలు',
    'nav.admin': 'అడ్మిన్',
    'nav.profile': 'ప్రొఫైల్',
    'nav.notifications': 'నోటిఫికేషన్లు',
    'nav.findCenters': 'కేంద్రాలు కనుగొనండి',
    'nav.signIn': 'సైన్ ఇన్ చేయండి',
    'nav.logout': 'లాగ్ అవుట్',
    'nav.more': 'మరిన్ని',
    'nav.explore': 'అన్వేషించండి',
    'nav.navigation': 'నావిగేషన్',
    'nav.account': 'ఖాతా',
    
    // ========== ల్యాండింగ్ పేజీ ==========
    'landing.hero.badge': 'AI-శక్తివంతమైన పరిష్కారం',
    'landing.hero.title': 'ఇ-వేస్ట్‌ను స్థిరమైన భవిష్యత్తుగా మార్చండి',
    'landing.hero.subtitle': 'వేలాది మంది మార్పు తీసుకురావడంలో చేరండి. మా AI-శక్తివంతమైన ప్లాట్‌ఫారం ఇ-వేస్ట్ నిర్వహణను సులభం, బహుమతిగా మరియు ప్రభావంగా చేస్తుంది.',
    'landing.hero.getStarted': 'ప్రారంభించండి',
    'landing.hero.tryAI': 'AI గుర్తింపు ప్రయత్నించండి',
    'landing.stats.users': 'నమోదైన వినియోగదారులు',
    'landing.stats.recycled': 'ఇ-వేస్ట్ రీసైకిల్ చేయబడింది',
    'landing.stats.centers': 'సేకరణ కేంద్రాలు',
    'landing.stats.accuracy': 'AI ఖచ్చితత్వం',
    'landing.features.title': 'శక్తివంతమైన ఫీచర్లు',
    'landing.features.subtitle': 'ఇ-వేస్ట్‌ను బాధ్యతాయుతంగా నిర్వహించడానికి మరియు రివార్డ్‌లు సంపాదించడానికి అవసరమైన ప్రతిదీ',
    'landing.features.ai.title': 'AI గుర్తింపు',
    'landing.features.ai.desc': 'అధునాతన AI తో తక్షణమే ఇ-వేస్ట్‌ను గుర్తించండి',
    'landing.features.map.title': 'కేంద్రాలు కనుగొనండి',
    'landing.features.map.desc': 'సమీపంలోని రీసైక్లింగ్ సౌకర్యాలను సులభంగా కనుగొనండి',
    'landing.features.rewards.title': 'రివార్డ్‌లు సంపాదించండి',
    'landing.features.rewards.desc': 'ప్రతి రీసైకిల్ చేసిన పరికరానికి పాయింట్లు పొందండి',
    'landing.features.impact.title': 'ప్రభావాన్ని ట్రాక్ చేయండి',
    'landing.features.impact.desc': 'మీ పర్యావరణ సహకారాన్ని చూడండి',
    'landing.cta.title': 'మార్పు తీసుకురావడానికి సిద్ధంగా ఉన్నారా?',
    'landing.cta.subtitle': 'పర్యావరణ యోధుల మా కమ్యూనిటీలో చేరండి మరియు స్థిరమైన భవిష్యత్తు వైపు మీ ప్రయాణాన్ని ప్రారంభించండి. ప్రతి రీసైకిల్ చేసిన పరికరం ముఖ్యమైనది.',
    'landing.cta.signup': 'ఇప్పుడు సైన్ అప్ చేయండి',
    
    // ========== లాగిన్ / రిజిస్టర్ ==========
    'auth.welcomeBack': 'తిరిగి స్వాగతం',
    'auth.signInSubtitle': 'కొనసాగించడానికి మీ ఖాతాలోకి సైన్ ఇన్ చేయండి',
    'auth.createAccount': 'ఖాతాను సృష్టించండి',
    'auth.signUpSubtitle': 'మా కమ్యూనిటీలో చేరండి మరియు మార్పు తీసుకురావడం ప్రారంభించండి',
    'auth.email': 'ఇమెయిల్ చిరునామా',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.confirmPassword': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
    'auth.fullName': 'పూర్తి పేరు',
    'auth.phoneNumber': 'ఫోన్ నంబర్',
    'auth.preferredLanguage': 'ఇష్టపడే భాష',
    'auth.selectRole': 'పాత్రను ఎంచుకోండి',
    'auth.role.user': 'సాధారణ వినియోగదారు',
    'auth.role.admin': 'నిర్వాహకుడు',
    'auth.role.worker': 'రీసైక్లింగ్ కార్మికుడు',
    'auth.role.organization': 'సంస్థ',
    'auth.signIn': 'సైన్ ఇన్ చేయండి',
    'auth.signUp': 'సైన్ అప్ చేయండి',
    'auth.noAccount': 'ఖాతా లేదా?',
    'auth.hasAccount': 'ఇప్పటికే ఖాతా ఉందా?',
    'auth.signUpLink': 'సైన్ అప్ చేయండి',
    'auth.signInLink': 'సైన్ ఇన్ చేయండి',
    'auth.forgotPassword': 'పాస్‌వర్డ్ మరచిపోయారా?',
    'auth.rememberMe': 'నన్ను గుర్తుంచుకోండి',
    'auth.orContinueWith': 'లేదా కొనసాగించండి',
    'auth.google': 'గూగుల్',
    'auth.loginSuccess': 'లాగిన్ విజయవంతమైంది',
    'auth.signupSuccess': 'ఖాతా విజయవంతంగా సృష్టించబడింది',
    'auth.logoutSuccess': 'విజయవంతంగా లాగ్ అవుట్ చేయబడింది',
    
    // ========== డాష్‌బోర్డ్ ==========
    'dashboard.welcome': 'తిరిగి స్వాగతం',
    'dashboard.welcomeMessage': 'ఇది మీ పర్యావరణ ప్రభావ సారాంశం',
    'dashboard.overview': 'అవలోకనం',
    'dashboard.stats.recycled': 'మొత్తం ఇ-వేస్ట్ రీసైకిల్ చేయబడింది',
    'dashboard.stats.carbon': 'కార్బన్ ఫుట్‌ప్రింట్ సేవ్ చేయబడింది',
    'dashboard.stats.points': 'మొత్తం పాయింట్లు సంపాదించారు',
    'dashboard.stats.items': 'ఐటెమ్‌లు ప్రాసెస్ చేయబడ్డాయి',
    'dashboard.stats.rank': 'గ్లోబల్ ర్యాంక్',
    'dashboard.stats.level': 'ప్రస్తుత స్థాయి',
    'dashboard.stats.streak': 'రోజుల స్ట్రీక్',
    'dashboard.recentActivity': 'ఇటీవలి కార్యాచరణ',
    'dashboard.quickActions': 'త్వరిత చర్యలు',
    'dashboard.impactChart': 'పర్యావరణ ప్రభావం',
    'dashboard.monthlyProgress': 'నెలవారీ పురోగతి',
    'dashboard.achievements': 'ఇటీవలి విజయాలు',
    'dashboard.uploadDevice': 'పరికరాన్ని అప్‌లోడ్ చేయండి',
    'dashboard.findCenter': 'కేంద్రాన్ని కనుగొనండి',
    'dashboard.viewRewards': 'రివార్డ్‌లు చూడండి',
    'dashboard.joinEvent': 'ఈవెంట్‌లో చేరండి',
    'dashboard.learnMore': 'మరింత తెలుసుకోండి',
    'dashboard.seeAll': 'అన్నీ చూడండి',
    'dashboard.noActivity': 'ఇటీవలి కార్యాచరణ లేదు',
    'dashboard.getStarted': 'మీ మొదటి పరికరాన్ని అప్‌లోడ్ చేయడం ద్వారా ప్రారంభించండి',
    
    // ========== అప్‌లోడ్ పేజీ ==========
    'upload.title': 'AI గుర్తింపు కోసం ఇ-వేస్ట్ అప్‌లోడ్ చేయండి',
    'upload.subtitle': 'తక్షణ గుర్తింపు కోసం మీ ఎలక్ట్రానిక్ వ్యర్థాల చిత్రాలను అప్‌లోడ్ చేయండి',
    'upload.dragDrop': 'ఇక్కడ చిత్రాలను లాగి వదలండి, లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి',
    'upload.supportedFormats': 'మద్దతు ఉన్న ఫార్మాట్లు: JPG, PNG, WebP',
    'upload.maxSize': 'గరిష్ట ఫైల్ పరిమాణం: 10MB',
    'upload.analyze': 'పరికరాన్ని విశ్లేషించండి',
    'upload.analyzing': 'విశ్లేషిస్తోంది...',
    'upload.results': 'గుర్తింపు ఫలితాలు',
    'upload.deviceType': 'పరికర రకం',
    'upload.confidence': 'విశ్వాసం',
    'upload.condition': 'పరిస్థితి',
    'upload.estimatedValue': 'అంచనా విలువ',
    'upload.recyclingMethod': 'రీసైక్లింగ్ పద్ధతి',
    'upload.nearestCenter': 'సమీప కేంద్రం',
    'upload.schedule': 'పికప్ షెడ్యూల్ చేయండి',
    'upload.selfDrop': 'స్వయంగా డ్రాప్-ఆఫ్',
    'upload.saveResults': 'ఫలితాలను సేవ్ చేయండి',
    'upload.uploadAnother': 'మరొకటి అప్‌లోడ్ చేయండి',
    'upload.history': 'అప్‌లోడ్ చరిత్ర',
    'upload.noResults': 'ఇంకా ఫలితాలు లేవు',
    'upload.uploadFirst': 'ఫలితాలను చూడటానికి మీ మొదటి పరికరాన్ని అప్‌లోడ్ చేయండి',
    
    // ========== మ్యాప్ పేజీ ==========
    'map.title': 'రీసైక్లింగ్ కేంద్రాలను కనుగొనండి',
    'map.subtitle': 'సమీపంలోని ఇ-వేస్ట్ సేకరణ సౌకర్యాలను కనుగొనండి',
    'map.searchLocation': 'స్థానాన్ని శోధించండి...',
    'map.filterByService': 'సేవ ద్వారా ఫిల్టర్ చేయండి',
    'map.allServices': 'అన్ని సేవలు',
    'map.pickup': 'పికప్ అందుబాటులో ఉంది',
    'map.dropoff': 'డ్రాప్-ఆఫ్',
    'map.buyback': 'బైబ్యాక్',
    'map.certified': 'ప్రమాణీకరించబడినది',
    'map.nearby': 'సమీప కేంద్రాలు',
    'map.distance': 'దూరం',
    'map.openNow': 'ఇప్పుడు తెరిచి ఉంది',
    'map.closed': 'మూసివేయబడింది',
    'map.opensAt': 'తెరుచుకుంటుంది',
    'map.closesAt': 'మూసుకుంటుంది',
    'map.getDirections': 'దిశలను పొందండి',
    'map.callCenter': 'కేంద్రానికి కాల్ చేయండి',
    'map.viewDetails': 'వివరాలను చూడండి',
    'map.services': 'సేవలు',
    'map.hours': 'ఆపరేటింగ్ గంటలు',
    'map.contact': 'సంప్రదించండి',
    'map.ratings': 'రేటింగ్‌లు',
    'map.reviews': 'సమీక్షలు',
    
    // ========== రివార్డ్స్ పేజీ ==========
    'rewards.title': 'రివార్డ్స్ షాప్',
    'rewards.subtitle': 'ఉత్తేజకరమైన రివార్డ్‌ల కోసం మీ పాయింట్లను రిడీమ్ చేయండి',
    'rewards.yourPoints': 'మీ పాయింట్లు',
    'rewards.availablePoints': 'అందుబాటులో ఉన్న పాయింట్లు',
    'rewards.pointsHistory': 'పాయింట్ల చరిత్ర',
    'rewards.redeem': 'రిడీమ్ చేయండి',
    'rewards.redeemed': 'రిడీమ్ చేయబడింది',
    'rewards.pointsRequired': 'పాయింట్లు',
    'rewards.categories': 'వర్గాలు',
    'rewards.all': 'అన్ని',
    'rewards.giftCards': 'గిఫ్ట్ కార్డ్‌లు',
    'rewards.products': 'ఉత్పత్తులు',
    'rewards.vouchers': 'వోచర్లు',
    'rewards.donations': 'విరాళాలు',
    'rewards.inStock': 'స్టాక్‌లో ఉంది',
    'rewards.outOfStock': 'స్టాక్ అయిపోయింది',
    'rewards.confirmRedeem': 'రిడెంప్షన్‌ను నిర్ధారించండి',
    'rewards.confirmMessage': 'మీరు ఖచ్చితంగా ఈ రివార్డ్‌ను రిడీమ్ చేయాలనుకుంటున్నారా?',
    'rewards.success': 'రివార్డ్ విజయవంతంగా రిడీమ్ చేయబడింది!',
    'rewards.insufficient': 'తగిన పాయింట్లు లేవు',
    'rewards.myRewards': 'నా రివార్డ్‌లు',
    'rewards.noRewards': 'ఇంకా రివార్డ్‌లు లేవు',
    'rewards.earnMore': 'రీసైక్లింగ్ చేయడం ద్వారా మరిన్ని పాయింట్లు సంపాదించండి',
    
    // ========== కమ్యూనిటీ పేజీ ==========
    'community.title': 'కమ్యూనిటీ',
    'community.subtitle': 'ప్రపంచవ్యాప్తంగా పర్యావరణ యోధులతో కనెక్ట్ అవ్వండి',
    'community.feed': 'కమ్యూనిటీ ఫీడ్',
    'community.trending': 'ట్రెండింగ్',
    'community.following': 'ఫాలో అవుతున్నారు',
    'community.myPosts': 'నా పోస్ట్‌లు',
    'community.createPost': 'పోస్ట్ సృష్టించండి',
    'community.whatsOnMind': 'మీ మనసులో ఏముంది?',
    'community.shareThoughts': 'మీ ఆలోచనలను భాగస్వామ్యం చేయండి...',
    'community.post': 'పోస్ట్ చేయండి',
    'community.cancel': 'రద్దు చేయండి',
    'community.like': 'లైక్',
    'community.comment': 'వ్యాఖ్య',
    'community.share': 'షేర్',
    'community.follow': 'ఫాలో చేయండి',
    'community.unfollow': 'అన్‌ఫాలో చేయండి',
    'community.likes': 'లైక్‌లు',
    'community.comments': 'వ్యాఖ్యలు',
    'community.replies': 'ప్రత్యుత్తరాలు',
    'community.writeComment': 'వ్యాఖ్యను రాయండి...',
    'community.viewMore': 'మరిన్ని చూడండి',
    'community.topContributors': 'టాప్ కంట్రిబ్యూటర్లు',
    'community.suggestedUsers': 'సూచించబడిన వినియోగదారులు',
    'community.noPosts': 'ఇంకా పోస్ట్‌లు లేవు',
    'community.beFirst': 'పోస్ట్ చేసిన మొదటి వ్యక్తి అవ్వండి!',
    
    // ========== విద్య పేజీ ==========
    'education.title': 'విద్యా కేంద్రం',
    'education.subtitle': 'ఇ-వేస్ట్ నిర్వహణ మరియు స్థిరత్వం గురించి తెలుసుకోండి',
    'education.courses': 'కోర్సులు',
    'education.guides': 'గైడ్‌లు',
    'education.videos': 'వీడియోలు',
    'education.quizzes': 'క్విజ్‌లు',
    'education.certifications': 'ప్రమాణపత్రాలు',
    'education.browse': 'కోర్సులను బ్రౌజ్ చేయండి',
    'education.featured': 'ఫీచర్ చేయబడినవి',
    'education.popular': 'జనాదరణ పొందినవి',
    'education.new': 'కొత్తవి',
    'education.beginner': 'ప్రారంభకులు',
    'education.intermediate': 'మధ్యస్థ',
    'education.advanced': 'అధునాతన',
    'education.enroll': 'ఇప్పుడు నమోదు చేసుకోండి',
    'education.enrolled': 'నమోదు చేసుకున్నారు',
    'education.continue': 'కొనసాగించండి',
    'education.completed': 'పూర్తయింది',
    'education.progress': 'పురోగతి',
    'education.lessons': 'పాఠాలు',
    'education.duration': 'వ్యవధి',
    'education.certificate': 'ప్రమాణపత్రం',
    'education.takeQuiz': 'క్విజ్ తీసుకోండి',
    'education.score': 'స్కోర్',
    'education.passed': 'ఉత్తీర్ణత',
    'education.failed': 'విఫలమైంది',
    'education.retake': 'మళ్ళీ తీసుకోండి',
    
    // ========== లీడర్‌బోర్డ్ పేజీ ==========
    'leaderboard.title': 'లీడర్‌బోర్డ్',
    'leaderboard.subtitle': 'మార్పు తీసుకురావడంలో టాప్ పర్యావరణ యోధులు',
    'leaderboard.global': 'గ్లోబల్',
    'leaderboard.regional': 'ప్రాంతీయ',
    'leaderboard.friends': 'స్నేహితులు',
    'leaderboard.thisWeek': 'ఈ వారం',
    'leaderboard.thisMonth': 'ఈ నెల',
    'leaderboard.allTime': 'అన్ని సమయాలు',
    'leaderboard.rank': 'ర్యాంక్',
    'leaderboard.user': 'వినియోగదారు',
    'leaderboard.points': 'పాయింట్లు',
    'leaderboard.recycled': 'రీసైకిల్ చేయబడింది',
    'leaderboard.level': 'స్థాయి',
    'leaderboard.yourRank': 'మీ ర్యాంక్',
    'leaderboard.topPerformers': 'టాప్ పెర్ఫార్మర్లు',
    'leaderboard.risingStars': 'రైజింగ్ స్టార్స్',
    'leaderboard.viewProfile': 'ప్రొఫైల్ చూడండి',
    'leaderboard.challenge': 'సవాలు',
    'leaderboard.noData': 'డేటా అందుబాటులో లేదు',
    
    // ========== ఈవెంట్స్ పేజీ ==========
    'events.title': 'ఈవెంట్స్ క్యాలెండర్',
    'events.subtitle': 'కమ్యూనిటీ ఈవెంట్లు మరియు సేకరణ డ్రైవ్‌లలో చేరండి',
    'events.upcoming': 'రాబోయే ఈవెంట్లు',
    'events.past': 'గత ఈవెంట్లు',
    'events.myEvents': 'నా ఈవెంట్లు',
    'events.all': 'అన్ని ఈవెంట్లు',
    'events.workshops': 'వర్క్‌షాప్‌లు',
    'events.drives': 'సేకరణ డ్రైవ్‌లు',
    'events.webinars': 'వెబినార్లు',
    'events.register': 'నమోదు చేసుకోండి',
    'events.registered': 'నమోదు చేసుకున్నారు',
    'events.unregister': 'నమోదు రద్దు చేయండి',
    'events.date': 'తేదీ',
    'events.time': 'సమయం',
    'events.location': 'స్థానం',
    'events.online': 'ఆన్‌లైన్',
    'events.offline': 'ఆఫ్‌లైన్',
    'events.hybrid': 'హైబ్రిడ్',
    'events.participants': 'పాల్గొనేవారు',
    'events.seats': 'సీట్లు అందుబాటులో ఉన్నాయి',
    'events.full': 'ఈవెంట్ నిండిపోయింది',
    'events.details': 'ఈవెంట్ వివరాలు',
    'events.addToCalendar': 'క్యాలెండర్‌కు జోడించండి',
    'events.share': 'ఈవెంట్‌ను షేర్ చేయండి',
    'events.noEvents': 'షెడ్యూల్ చేసిన ఈవెంట్లు లేవు',
    
    // ========== విశ్లేషణలు పేజీ ==========
    'analytics.title': 'విశ్లేషణలు & రిపోర్ట్లు',
    'analytics.subtitle': 'మీ పర్యావరణ ప్రభావాన్ని ట్రాక్ చేయండి',
    'analytics.overview': 'అవలోకనం',
    'analytics.insights': 'అంతర్దృష్టులు',
    'analytics.reports': 'రిపోర్ట్లు',
    'analytics.export': 'ఎగుమతి',
    'analytics.period': 'కాలం',
    'analytics.today': 'ఈరోజు',
    'analytics.week': 'ఈ వారం',
    'analytics.month': 'ఈ నెల',
    'analytics.year': 'ఈ సంవత్సరం',
    'analytics.custom': 'కస్టమ్ పరిధి',
    'analytics.totalImpact': 'మొత్తం ప్రభావం',
    'analytics.carbonSaved': 'కార్బన్ సేవ్ చేయబడింది',
    'analytics.deviceTypes': 'పరికర రకాలు',
    'analytics.recyclingTrends': 'రీసైక్లింగ్ ట్రెండ్‌లు',
    'analytics.comparison': 'పోలిక',
    'analytics.vsLastMonth': 'గత నెలతో పోలిస్తే',
    'analytics.growth': 'వృద్ధి',
    'analytics.decline': 'క్షీణత',
    'analytics.stable': 'స్థిరమైనది',
    'analytics.downloadPDF': 'PDF డౌన్‌లోడ్ చేయండి',
    'analytics.downloadCSV': 'CSV డౌన్‌లోడ్ చేయండి',
    'analytics.share': 'రిపోర్ట్ షేర్ చేయండి',
    
    // ========== అడ్మిన్ పేజీ ==========
    'admin.title': 'అడ్మిన్ ప్యానెల్',
    'admin.subtitle': 'ప్లాట్‌ఫారం మరియు వినియోగదారులను నిర్వహించండి',
    'admin.dashboard': 'డాష్‌బోర్డ్',
    'admin.users': 'వినియోగదారులు',
    'admin.content': 'కంటెంట్',
    'admin.settings': 'సెట్టింగ్‌లు',
    'admin.reports': 'రిపోర్ట్లు',
    'admin.totalUsers': 'మొత్తం వినియోగదారులు',
    'admin.activeUsers': 'క్రియాశీల వినియోగదారులు',
    'admin.newUsers': 'కొత్త వినియోగదారులు',
    'admin.totalCenters': 'మొత్తం కేంద్రాలు',
    'admin.pendingApprovals': 'పెండింగ్ ఆమోదాలు',
    'admin.userManagement': 'వినియోగదారు నిర్వహణ',
    'admin.searchUsers': 'వినియోగదారులను శోధించండి...',
    'admin.filterByRole': 'పాత్ర ద్వారా ఫిల్టర్ చేయండి',
    'admin.filterByStatus': 'స్థితి ద్వారా ఫిల్టర్ చేయండి',
    'admin.active': 'క్రియాశీలం',
    'admin.inactive': 'నిష్క్రియం',
    'admin.suspended': 'సస్పెండ్ చేయబడింది',
    'admin.viewUser': 'వినియోగదారుని చూడండి',
    'admin.editUser': 'వినియోగదారుని సవరించండి',
    'admin.suspendUser': 'వినియోగదారుని సస్పెండ్ చేయండి',
    'admin.deleteUser': 'వినియోగదారుని తొలగించండి',
    'admin.approve': 'ఆమోదించండి',
    'admin.reject': 'తిరస్కరించండి',
    'admin.bulkActions': 'బల్క్ చర్యలు',
    'admin.export': 'ఎగుమతి',
    'admin.systemSettings': 'సిస్టమ్ సెట్టింగ్‌లు',
    'admin.notifications': 'నోటిఫికేషన్లు',
    'admin.maintenance': 'నిర్వహణ',
    
    // ========== ప్రొఫైల్ పేజీ ==========
    'profile.title': 'ప్రొఫైల్',
    'profile.subtitle': 'మీ ఖాతా మరియు ప్రాధాన్యతలను నిర్వహించండి',
    'profile.personalInfo': 'వ్యక్తిగత సమాచారం',
    'profile.accountSettings': 'ఖాతా సెట్టింగ్‌లు',
    'profile.privacy': 'గోప్యత',
    'profile.security': 'భద్రత',
    'profile.edit': 'ప్రొఫైల్‌ను సవరించండి',
    'profile.save': 'మార్పులను సేవ్ చేయండి',
    'profile.cancel': 'రద్దు చేయండి',
    'profile.name': 'పూర్తి పేరు',
    'profile.email': 'ఇమెయిల్ చిరునామా',
    'profile.phone': 'ఫోన్ నంబర్',
    'profile.bio': 'బయో',
    'profile.location': 'స్థానం',
    'profile.website': 'వెబ్‌సైట్',
    'profile.language': 'భాష',
    'profile.timezone': 'టైమ్‌జోన్',
    'profile.changePassword': 'పాస్‌వర్డ్ మార్చండి',
    'profile.currentPassword': 'ప్రస్తుత పాస్‌వర్డ్',
    'profile.newPassword': 'కొత్త పాస్‌వర్డ్',
    'profile.confirmPassword': 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
    'profile.emailNotifications': 'ఇమెయిల్ నోటిఫికేషన్లు',
    'profile.pushNotifications': 'పుష్ నోటిఫికేషన్లు',
    'profile.smsNotifications': 'SMS నోటిఫికేషన్లు',
    'profile.publicProfile': 'పబ్లిక్ ప్రొఫైల్',
    'profile.showStats': 'గణాంకాలను చూపించు',
    'profile.showActivity': 'కార్యాచరణను చూపించు',
    'profile.deleteAccount': 'ఖాతాను తొలగించు',
    'profile.deactivateAccount': 'ఖాతాను నిష్క్రియం చేయండి',
    'profile.verified': 'ధృవీకరించబడింది',
    'profile.notVerified': 'ధృవీకరించబడలేదు',
    'profile.verify': 'ధృవీకరించండి',
    
    // ========== నోటిఫికేషన్లు పేజీ ==========
    'notifications.title': 'నోటిఫికేషన్లు',
    'notifications.subtitle': 'మీ కార్యాచరణతో అప్‌డేట్‌గా ఉండండి',
    'notifications.all': 'అన్ని',
    'notifications.unread': 'చదవనివి',
    'notifications.read': 'చదివినవి',
    'notifications.markAllRead': 'అన్నింటినీ చదివినట్లు గుర్తించు',
    'notifications.clear': 'అన్నింటినీ క్లియర్ చేయండి',
    'notifications.settings': 'నోటిఫికేషన్ సెట్టింగ్‌లు',
    'notifications.noNew': 'కొత్త నోటిఫికేషన్లు లేవు',
    'notifications.noNotifications': 'ఇంకా నోటిఫికేషన్లు లేవు',
    'notifications.empty': 'మీరు అన్నీ పట్టుకున్నారు!',
    'notifications.types.system': 'సిస్టమ్',
    'notifications.types.rewards': 'రివార్డ్స్',
    'notifications.types.community': 'కమ్యూనిటీ',
    'notifications.types.events': 'ఈవెంట్స్',
    'notifications.types.admin': 'అడ్మిన్',
    'notifications.delete': 'తొలగించు',
    'notifications.mute': 'మ్యూట్ చేయండి',
    'notifications.unmute': 'అన్‌మ్యూట్ చేయండి',
    
    // ========== సాధారణ అంశాలు ==========
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.save': 'సేవ్ చేయండి',
    'common.cancel': 'రద్దు చేయండి',
    'common.edit': 'సవరించండి',
    'common.delete': 'తొలగించండి',
    'common.confirm': 'నిర్ధారించండి',
    'common.close': 'మూసివేయండి',
    'common.back': 'వెనక్కి',
    'common.next': 'తదుపరి',
    'common.previous': 'మునుపటి',
    'common.search': 'శోధించండి',
    'common.filter': 'ఫిల్టర్',
    'common.sort': 'క్రమబద్ధీకరించు',
    'common.view': 'చూడండి',
    'common.viewAll': 'అన్నీ చూడండి',
    'common.showMore': 'మరిన్ని చూపించు',
    'common.showLess': 'తక్కువ చూపించు',
    'common.learnMore': 'మరింత తెలుసుకోండి',
    'common.readMore': 'మరింత చదవండి',
    'common.seeAll': 'అన్నీ చూడండి',
    'common.yes': 'అవును',
    'common.no': 'లేదు',
    'common.ok': 'సరే',
    'common.apply': 'వర్తింపజేయండి',
    'common.reset': 'రీసెట్ చేయండి',
    'common.clear': 'క్లియర్ చేయండి',
    'common.submit': 'సమర్పించండి',
    'common.send': 'పంపండి',
    'common.upload': 'అప్‌లోడ్ చేయండి',
    'common.download': 'డౌన్‌లోడ్ చేయండి',
    'common.share': 'షేర్ చేయండి',
    'common.copy': 'కాపీ చేయండి',
    'common.copied': 'కాపీ చేయబడింది!',
    'common.update': 'అప్‌డేట్ చేయండి',
    'common.refresh': 'రిఫ్రెష్ చేయండి',
    'common.retry': 'మళ్ళీ ప్రయత్నించండి',
    'common.undo': 'అన్‌డు చేయండి',
    'common.redo': 'రీడు చేయండి',
    'common.settings': 'సెట్టింగ్‌లు',
    'common.help': 'సహాయం',
    'common.support': 'మద్దతు',
    'common.feedback': 'ఫీడ్‌బ్యాక్',
    'common.report': 'రిపోర్ట్ చేయండి',
    'common.success': 'విజయం',
    'common.error': 'దోషం',
    'common.warning': 'హెచ్చరిక',
    'common.info': 'సమాచారం',
    'common.required': 'అవసరం',
    'common.optional': 'ఐచ్ఛికం',
    'common.select': 'ఎంచుకోండి',
    'common.choose': 'ఎంచుకోండి',
    'common.browse': 'బ్రౌజ్ చేయండి',
    'common.noResults': 'ఫలితాలు కనుగొనబడలేదు',
    'common.noData': 'డేటా అందుబాటులో లేదు',
    'common.comingSoon': 'త్వరలో వస్తోంది',
    'common.new': 'కొత్తది',
    'common.popular': 'జనాదరణ పొందినది',
    'common.featured': 'ఫీచర్ చేయబడినది',
    'common.recommended': 'సిఫార్సు చేయబడినది',
    'common.trending': 'ట్రెండింగ్',
    'common.today': 'ఈరోజు',
    'common.yesterday': 'నిన్న',
    'common.thisWeek': 'ఈ వారం',
    'common.thisMonth': 'ఈ నెల',
    'common.thisYear': 'ఈ సంవత్సరం',
    'common.total': 'మొత్తం',
    'common.active': 'క్రియాశీలం',
    'common.inactive': 'నిష్క్రియం',
    'common.pending': 'పెండింగ్',
    'common.completed': 'పూర్తయింది',
    'common.failed': 'విఫలమైంది',
    'common.processing': 'ప్రాసెస్ అవుతోంది',
    'common.kg': 'కిలోలు',
    'common.points': 'పాయింట్లు',
    'common.level': 'స్థాయి',
    'common.rank': 'ర్యాంక్',
    
    // ========== సమయం & తేదీలు ==========
    'time.justNow': 'ఇప్పుడే',
    'time.minuteAgo': 'నిమిషం క్రితం',
    'time.minutesAgo': 'నిమిషాల క్రితం',
    'time.hourAgo': 'గంట క్రితం',
    'time.hoursAgo': 'గంటల క్రితం',
    'time.dayAgo': 'రోజు క్రితం',
    'time.daysAgo': 'రోజుల క్రితం',
    'time.weekAgo': 'వారం క్రితం',
    'time.weeksAgo': 'వారాల క్రితం',
    'time.monthAgo': 'నెల క్రితం',
    'time.monthsAgo': 'నెలల క్రితం',
    'time.yearAgo': 'సంవత్సరం క్రితం',
    'time.yearsAgo': 'సంవత్సరాల క్రితం',
    
    // ========== దోష సందేశాలు ==========
    'error.general': 'ఏదో తప్పు జరిగింది',
    'error.network': 'నెట్‌వర్క్ దోషం. దయచేసి మీ కనెక్షన్‌ను తనిఖీ చేయండి',
    'error.notFound': 'కనుగొనబడలేదు',
    'error.unauthorized': 'అనధికార యాక్సెస్',
    'error.forbidden': 'యాక్సెస్ నిషేధించబడింది',
    'error.serverError': 'సర్వర్ దోషం. దయచేసి తర్వాత మళ్ళీ ప్రయత్నించండి',
    'error.invalidInput': 'చెల్లని ఇన్‌పుట్',
    'error.required': 'ఈ ఫీల్డ్ అవసరం',
    'error.invalidEmail': 'చెల్లని ఇమెయిల్ చిరునామా',
    'error.invalidPhone': 'చెల్లని ఫోన్ నంబర్',
    'error.passwordMismatch': 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
    'error.weakPassword': 'పాస్‌వర్డ్ చాలా బలహీనంగా ఉంది',
    'error.uploadFailed': 'అప్‌లోడ్ విఫలమైంది',
    'error.deleteFailed': 'తొలగించడం విఫలమైంది',
    'error.updateFailed': 'అప్‌డేట్ విఫలమైంది',
    
    // ========== విజయ సందేశాలు ==========
    'success.saved': 'విజయవంతంగా సేవ్ చేయబడింది',
    'success.updated': 'విజయవంతంగా అప్‌డేట్ చేయబడింది',
    'success.deleted': 'విజయవంతంగా తొలగించబడింది',
    'success.uploaded': 'విజయవంతంగా అప్‌లోడ్ చేయబడింది',
    'success.sent': 'విజయవంతంగా పంపబడింది',
    'success.copied': 'క్లిప్‌బోర్డ్‌కు కాపీ చేయబడింది',
    
    // ========== భాష ఎంపిక ==========
    'language.select': 'భాషను ఎంచుకోండి',
    'language.english': 'English',
    'language.hindi': 'हिन्दी (Hindi)',
    'language.telugu': 'తెలుగు (Telugu)',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage') as Language;
    if (savedLanguage && ['en', 'hi', 'te'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Set language and save to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferredLanguage', lang);
    
    // Update HTML lang attribute for accessibility
    document.documentElement.lang = lang;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
